server:
  port: 8004
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/studySpringCloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true

  application:
    name: provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.139.128:2181
