server:
  port: 3344
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:ct7cxz/springcloud-config.git #git上的ssh地址
          uri: https://github.com/ct7cxz/springcloud-config.git
          search-paths:
            - springcloud-config    #搜索路径名
          private-key:
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEAwvj0FoE76WlZxeAjLSb8mur1odeSIgtHB6VIMf42ViAFMeeJN0QN
            ZiXrusQDVfnE/cssj572yIF55bA4VIaIw9DhZ4D/vw15Emhwm5HdWheqJy34wNWoTMftNe
            xcXsQRX2wgMYTyQC6+G8EYmeEgcByV6mC0qrvjHJkQb+/2k2AnnQpTtP1EXNPpdWujbby4
            /LUqVC7wmesElk57Ex/r6gJQ/icl/9l14RdBvsnPUHbD8Xg6etxCl0vIfl1TzvhIo5BAxu
            zzXQBiI1wD7XbrQDCP0nHiY5cPujAKBnqH6cY+Q5LHW1A49hZrEvWQAa/cVlea/88m4hjx
            gf02GHH3RAMrJ3ytBQWTKNmHpnI6atnpixzk8PCwOaMDqjZvuyLgGfoSCZsIn2oq5T8a8M
            EhJgImhJEQSAbvLBzhRiIjlKo69P0Je7Evxhf5vohVPrymmR3tMWR63IPbX62GEDJeWw9U
            jtQVGiGawyx1u7R31vgfmVB26vHL9a3eUfL32VWJAAAFiLlihry5Yoa8AAAAB3NzaC1yc2
            EAAAGBAML49BaBO+lpWcXgIy0m/Jrq9aHXkiILRwelSDH+NlYgBTHniTdEDWYl67rEA1X5
            xP3LLI+e9siBeeWwOFSGiMPQ4WeA/78NeRJocJuR3VoXqict+MDVqEzH7TXsXF7EEV9sID
            GE8kAuvhvBGJnhIHAclepgtKq74xyZEG/v9pNgJ50KU7T9RFzT6XVro228uPy1KlQu8Jnr
            BJZOexMf6+oCUP4nJf/ZdeEXQb7Jz1B2w/F4OnrcQpdLyH5dU874SKOQQMbs810AYiNcA+
            1260Awj9Jx4mOXD7owCgZ6h+nGPkOSx1tQOPYWaxL1kAGv3FZXmv/PJuIY8YH9Nhhx90QD
            Kyd8rQUFkyjZh6ZyOmrZ6Ysc5PDwsDmjA6o2b7si4Bn6EgmbCJ9qKuU/GvDBISYCJoSREE
            gG7ywc4UYiI5SqOvT9CXuxL8YX+b6IVT68ppkd7TFketyD21+thhAyXlsPVI7UFRohmsMs
            dbu0d9b4H5lQdurxy/Wt3lHy99lViQAAAAMBAAEAAAGAHUDPFqVTQOUepBLKFFc6JWBFdH
            /snBEHGj2RRHb43hk1zlQIAXPDcuUTplUMjxTHmrCmQfI+4rySdoTnHr+Eu6SWfTocpSS3
            Wqyy4JSVGpRcYj6CiSRFeSeyDpolDc7rMF7/wY5J7plUysNBFq1xeYDAeYcC9G72V28byT
            ++xkPyDZzkDE7HuAnPiF+bCLb9JmVkMXdNgDqD2K1zx93NPrIURt3G1Mli51/e7GpJIbCA
            G7XHSHHNx/eF4HfOQEp+EDC3iLa9rHrdrq3BEkkQVbnatp2trYW86OCypRvWvQsfMxrDN/
            KP2+z4SaHTc1WtiYs7zOcNouZKFm/t+qR9NcGVNL7tQ81hXJxpPGnUE+rMDiOHWP1cXWRA
            Gd5JoZMnJc+YDN5tIIS+LXlot5OCggK6aUTUS4B3EUSBXkkr9f6hxHgDw223ArGbp5ogPt
            qAgVwjol5/sepBvqo1ck8IDMdDIMPgVCqErfEk/QUvpHPtqTcRzXxTi2zVgNvu2f0BAAAA
            wCRF83zv4n+G+ZyRijHkXxtn386hi+bHIM6AriycNd8JOBiCJ74rapW+Wb2NkhwQI402Uy
            EaGwjVoqn42U27nBOnkR/x7G+sCzImN++BzeJ9Croc5XyA69AV11Dmskvt+NG1Wjv28ZNX
            dVUMqsXF9MsddYceDF2wAD8MY03SGHddeDG8n/eOZ2fiKvcJK+375nev1hedSmgSh5C2c6
            WOyodgkQFNH1OpAT9jmfk8L0Hz+AESKN/qdEjbp8G0prTbxwAAAMEA918OEdecZIxUIvGC
            oh0BBXknJUJtqOYe6L0yETSVxceTvsGrEO3VPVH9OuskuNaqmYwApnDlkFTfsKilIdS6Dq
            RnPkfnT91GeDUcE2h8ZEFSt1Gvdmb3aIjEWNwnhWrsF/EOxlnj5UukzfR1Y9uGtnqTZwx2
            undlFLaIUEVmSNdtn3+4XZCgKALsTI2rMuG9MEeu/TIygUqSPhXM6NgI5P8JtxQ3tzNW21
            ZYSxzOmGn09ECgqJquvLuamFgvPyUhAAAAwQDJxf54akf3/yeAZENh8iZ0CkQjMNqtHcE8
            kN/GCJX7BQnM2ybKRdxGr/XO0kkzax9gj2AhvFSwxMyFLZt+FkdUYgvwzgntAuIhP6TAVj
            7nkNuI5w2vHBs1bK/I8kKXBCNdvIazRQx9diouu9CcvwR84RjoepZ45TR++i62HXSaTYlG
            wm7j0qdMa8qVGxTeF7GRidtqKb3XLTbiBFZj7GEuibiUIxS1kbCJaa6UVWlP9S7pJltITI
            Rnnenpu0hUu2kAAAARMTk2MzgyMDU0MUBxcS5jb20BAg==
      label: master
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/studySpringCloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
      # 注册进入的eureka server地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: center-config
    prefer-ip-address: true
#rabbitMq相关配置，暴漏bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
