server:
  port: 80
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/studySpringCloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true

  application:
    name: consul-consumer-order #服务名称
  cloud:
    consul:
      host: localhost #ip地址
      port: 8500      #端口号
      discovery:
        service-name: ${spring.application.name}
