server:
  port: 80
spring:
  application:
    name: consumers-hystrix-order
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/studySpringCloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # 注册进入的eureka server地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/