server:
  port: 80
spring:
  application:
    name: consumers-order
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/studySpringCloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # 注册进入的eureka server地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/